In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("IMDB_Dataset.csv")
df.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [3]:
df.shape

(50000, 2)

In [4]:
print(df['sentiment'].value_counts())

sentiment
positive    25000
negative    25000
Name: count, dtype: int64


In [4]:
df['sentiment'] = df['sentiment'].map({
    'positive': 1,
    'negative': 0
})

In [5]:
df.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,1
1,A wonderful little production. <br /><br />The...,1
2,I thought this was a wonderful way to spend ti...,1
3,Basically there's a family where a little boy ...,0
4,"Petter Mattei's ""Love in the Time of Money"" is...",1


In [6]:
X = df['review'].values
y = df['sentiment'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
y_train, y_test

(array([0, 0, 1, ..., 0, 1, 1], dtype=int64),
 array([1, 1, 0, ..., 1, 0, 1], dtype=int64))

In [8]:
VOCAB_SIZE = 10000
MAX_LEN = 200          #length of a review is 200 max

tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<OOV>")    #OOV out of vocablary tokens will be replaced with <OOV>
tokenizer.fit_on_texts(X_train)     #converts vored in to tokes

In [9]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'and': 3,
 'a': 4,
 'of': 5,
 'to': 6,
 'is': 7,
 'br': 8,
 'in': 9,
 'it': 10,
 'i': 11,
 'this': 12,
 'that': 13,
 'was': 14,
 'as': 15,
 'for': 16,
 'with': 17,
 'movie': 18,
 'but': 19,
 'film': 20,
 'on': 21,
 'not': 22,
 'you': 23,
 'are': 24,
 'his': 25,
 'have': 26,
 'be': 27,
 'one': 28,
 'he': 29,
 'all': 30,
 'at': 31,
 'by': 32,
 'an': 33,
 'they': 34,
 'so': 35,
 'from': 36,
 'who': 37,
 'like': 38,
 'or': 39,
 'just': 40,
 'her': 41,
 'out': 42,
 'about': 43,
 'if': 44,
 "it's": 45,
 'has': 46,
 'there': 47,
 'some': 48,
 'what': 49,
 'good': 50,
 'more': 51,
 'very': 52,
 'when': 53,
 'up': 54,
 'no': 55,
 'time': 56,
 'my': 57,
 'even': 58,
 'she': 59,
 'would': 60,
 'which': 61,
 'only': 62,
 'story': 63,
 'really': 64,
 'see': 65,
 'their': 66,
 'had': 67,
 'can': 68,
 'me': 69,
 'well': 70,
 'were': 71,
 'we': 72,
 'than': 73,
 'much': 74,
 'bad': 75,
 'been': 76,
 'do': 77,
 'get': 78,
 'great': 79,
 'also': 80,
 'will': 81,
 'other': 82,
 '

In [10]:
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

In [11]:
X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN)
X_test_pad = pad_sequences(X_test_seq, maxlen=MAX_LEN)

In [12]:
X_train_pad

array([[ 145, 1084,   17, ...,  206,  352, 3857],
       [ 311,    6,  426, ...,   90,  104,   10],
       [   0,    0,    0, ...,    3,  711,   63],
       ...,
       [   0,    0,    0, ..., 1642,    3,  604],
       [   0,    0,    0, ...,  126, 7286,    1],
       [   0,    0,    0, ...,   71,   74, 2063]])

In [13]:
embedding_vector_features = 64 # feature representation
model = Sequential()
model.add(Embedding(VOCAB_SIZE, embedding_vector_features, input_length =MAX_LEN ))
model.add(SimpleRNN(100))
model.add(Dense(1, activation = "sigmoid"))
model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 200, 64)           640000    
                                                                 
 simple_rnn (SimpleRNN)      (None, 100)               16500     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 656,601
Trainable params: 656,601
Non-trainable params: 0
_________________________________________________________________
None


In [14]:
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

In [15]:
X_train_seq

[[198,
  49,
  11,
  802,
  2161,
  535,
  303,
  2,
  108,
  1908,
  2039,
  4325,
  6551,
  3,
  816,
  4845,
  13,
  1,
  2,
  1,
  228,
  2,
  6191,
  80,
  783,
  54,
  53,
  23,
  102,
  5,
  2,
  28,
  2010,
  103,
  37,
  26,
  35,
  120,
  1131,
  13,
  10,
  7,
  2367,
  1191,
  6,
  455,
  49,
  553,
  6,
  93,
  34,
  24,
  40,
  917,
  401,
  1,
  16,
  2,
  167,
  6,
  2994,
  25,
  1,
  4360,
  21,
  4,
  2946,
  13,
  46,
  76,
  222,
  74,
  127,
  9,
  82,
  3156,
  196,
  21,
  240,
  3,
  2,
  448,
  8,
  8,
  11,
  206,
  4983,
  145,
  22,
  64,
  28,
  16,
  1,
  75,
  366,
  303,
  4,
  20,
  19,
  10,
  206,
  27,
  308,
  13,
  1,
  1,
  15,
  2,
  1,
  1,
  116,
  440,
  3,
  1,
  1,
  15,
  2,
  1705,
  1,
  616,
  71,
  425,
  382,
  11,
  90,
  119,
  49,
  113,
  371,
  34,
  1,
  36,
  19,
  44,
  11,
  14,
  93,
  486,
  6831,
  16,
  4,
  365,
  1,
  1183,
  1,
  62,
  1,
  1,
  9,
  2,
  471,
  217,
  1015,
  6,
  4161,
  9,
  4,
  175,
  5,
  35,
  4

In [16]:
X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN)
X_test_pad = pad_sequences(X_test_seq, maxlen=MAX_LEN)


In [17]:
X_train_pad

array([[ 145, 1084,   17, ...,  206,  352, 3857],
       [ 311,    6,  426, ...,   90,  104,   10],
       [   0,    0,    0, ...,    3,  711,   63],
       ...,
       [   0,    0,    0, ..., 1642,    3,  604],
       [   0,    0,    0, ...,  126, 7286,    1],
       [   0,    0,    0, ...,   71,   74, 2063]])

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

VOCAB_SIZE = 10000
EMBEDDING_DIM = 100
MAX_LEN = 200   # sequence length

model = Sequential([
    Embedding(input_dim=VOCAB_SIZE,
              output_dim=EMBEDDING_DIM,
              input_shape=(MAX_LEN,)),
    SimpleRNN(64),
    Dense(1, activation='sigmoid')
])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 200, 100)          1000000   
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 64)                10560     
                                                                 
 dense_1 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1,010,625
Trainable params: 1,010,625
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 200, 100)          1000000   
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 64)                10560     
                                                                 
 dense_1 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1,010,625
Trainable params: 1,010,625
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
# model training
model.fit(X_train_pad, y_train, validation_data = (X_test_pad, y_test), epochs = 10, batch_size = 64)

Epoch 1/10
625/625 [==============================] - 76s 122ms/step - loss: 0.5372 - accuracy: 0.7210 - val_loss: 0.4883 - val_accuracy: 0.7684
Epoch 2/10
625/625 [==============================] - 79s 126ms/step - loss: 0.4149 - accuracy: 0.8120 - val_loss: 0.5715 - val_accuracy: 0.6938
Epoch 3/10
625/625 [==============================] - 73s 117ms/step - loss: 0.4444 - accuracy: 0.8037 - val_loss: 0.4909 - val_accuracy: 0.7693
Epoch 4/10
625/625 [==============================] - 72s 115ms/step - loss: 0.4007 - accuracy: 0.8306 - val_loss: 0.5934 - val_accuracy: 0.6744
Epoch 5/10
625/625 [==============================] - 75s 120ms/step - loss: 0.3364 - accuracy: 0.8626 - val_loss: 0.4632 - val_accuracy: 0.7891
Epoch 6/10
625/625 [==============================] - 79s 127ms/step - loss: 0.3768 - accuracy: 0.8357 - val_loss: 0.5686 - val_accuracy: 0.7067
Epoch 7/10
625/625 [==============================] - 78s 125ms/step - loss: 0.3600 - accuracy: 0.8521 - val_loss: 0.4409 - val_ac

: 

In [22]:
y_pred = model.predict(X_test_pad)

313/313 [==============================] - 2s 7ms/step


In [23]:
y_pred = np.where(y_pred>0.4, 1,0)
y_pred

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [1]])

In [24]:
y_test

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [26]:
pd.DataFrame(confusion_matrix(y_test, y_pred))

,0,1
0,4044,917
1,951,4088


In [27]:
accuracy_score(y_test, y_pred)

0.8132

In [28]:
import pickle

model.save("sentiment_model.h5")

with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

In [29]:
%%writefile app.py
import streamlit as st
import numpy as np
import pickle
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences

# -------------------------------
# Load model and tokenizer
# -------------------------------
model = load_model("sentiment_model.h5")

with open("tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

MAX_LEN = 200   # same as training

# -------------------------------
# Streamlit UI
# -------------------------------
st.set_page_config(page_title="Sentiment Analysis App", layout="centered")

st.title("🧠 Sentiment Analysis Web App")
st.write("Binary Classification (Positive / Negative)")
st.write("Model Accuracy: **64%**")

# Text input
user_text = st.text_area("Enter your review or sentence:", height=150)

# Prediction button
if st.button("Predict Sentiment"):

    if len(user_text.strip()) == 0:
        st.warning("Please enter some text.")
    else:
        # Tokenization
        seq = tokenizer.texts_to_sequences([user_text])
        padded = pad_sequences(seq, maxlen=MAX_LEN, padding="post")

        # Prediction
        pred = model.predict(padded)[0][0]

        # Decision threshold
        sentiment = "Positive 😊" if pred > 0.5 else "Negative 😞"

        # Display result
        st.subheader("Prediction Result")
        st.write("Sentiment:", sentiment)
        st.write("Confidence Score:", round(float(pred), 3))


Writing app.py


In [31]:
from pyngrok import ngrok

In [32]:
!streamlit run app.py &>/content/logs.txt &

OSError: Background processes not supported.

In [ ]:
# Replace 'YOUR_AUTHTOKEN_HERE' with your actual token from https://dashboard.ngrok.com/get-started/your-authtoken
import os
from pyngrok import ngrok

AUTHTOKEN = "YOUR_AUTHTOKEN_HERE"
ngrok.set_auth_token(AUTHTOKEN)

public_url = ngrok.connect(8501)
public_url